### ISSUE TITLE
Problem install the package

### ISSUE THREAD

**Issue by kiaras** [logston/olimex-ekg-emg#5]
Hello,

I have Windows 7, and I have problem installing the olimex-ekg-emg package on Python 3.4 (it is 32 bit). I believe that it is complaining that I am missing some other packages. Can you tell me what other packages I need to have besides this so that I can successfully install this package?

Thanks

**Comment by logston** [comment]
Hi @kiaras,

Please post the error messages you get in the future. Here's a list of what this package requires.

``` python
    # from setup.py
    install_requires=[
        'pyserial>=2.7',
        'numpy>=1.9.1',
        'matplotlib>=1.4.2',
        'scipy>=0.15.1',
    ],
```
