### ISSUE TITLE
No data on "Figure 1" and random information on Arduino serial monitor.

### ISSUE THREAD

**Issue by xiutek** [logston/olimex-ekg-emg#6]
Finally I could install the olimex-ekg-emg new version and I run it on a python 3 virtual enviroment on terminal. The program and its dependeces installed fully on the enviroment but I cant get any data. Im using the Olimex shield mount on Arduino Uno with the example script provided by Olimex for electric guru.

Any Idea of what could be going wrong?

Im using a Lubuntu fresh install and did resolve all the dependece problems when installing olimex-ekg-emg on the python 3 virtual enviroment.

![2016-03-02-005412_1366x768_scrot](https://cloud.githubusercontent.com/assets/17224536/13452968/5daa2044-e012-11e5-899c-45682ca95fa1.png)

**Comment by logston** [comment]
High @xiutek. Please load the sketch provided in this repo for your arduino: 

https://github.com/logston/olimex-ekg-emg/blob/master/sketches/ShieldEkgEmg.ino

Also, make sure your baud rate is 115200.
