### ISSUE TITLE
White screen when trying to view data from olimex ekg/emg shield

### ISSUE THREAD

**Issue by Nuemii** [logston/olimex-ekg-emg#9]
Hello, 

When I run -U olimex-ekg-emg  on python3 I do see correctly the mock data files, but I get a white screen on matplotlib when I try to visualise my own data with arduino and its shield.

![image](https://cloud.githubusercontent.com/assets/20630041/17086603/f37d72b4-51f6-11e6-9f7b-2aff6df48e6d.png)

**Comment by logston** [comment]
Just released 0.2.0. Let me know if it works for you.
